name: Pipeline CI/CD
run-name: Pipeline CI/CD executada por ${{ github.actor }} em ${{ github.run_number }}

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código do projeto
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"
      - name: Execução do comando Build
        working-directory: ./src
        run: dotnet build Review-Filmes.sln
  
  release:
    name: Criação da Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Obtendo o código do projeto
        uses: actions/checkout@v4
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build e Push da Imagem
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./src
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: | 
            gabrieloliver001/projeto-cicd-movies:latest
            gabrieloliver001/projeto-cicd-movies:v1.0.${{ github.run_number }}